version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_securescreen
        environment:
            POSTGRES_DB: securescreen
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
